"use server";

import { prisma } from "@/lib/prisma";
import { requireAuth } from "@/lib/session";
import { revalidatePath } from "next/cache";
import { awardXp } from "@/lib/gamification/xp-engine";
import { ingestDocument } from "@/lib/ai/ingest";
import { createEvidenceSnapshot } from "@/lib/cascade/snapshot";
import { runImpactAnalysis } from "@/lib/cascade/impact";
import type { PocDeliverable } from "@/lib/poc-deliverables-types";
import { DEFAULT_POC_DELIVERABLES } from "@/lib/poc-deliverables-types";
import { Prisma } from "@prisma/client";

export interface ServiceEntry {
  domain: string;
  name: string;
  purpose: string;
  type: "REST" | "GraphQL" | "gRPC" | "AsyncAPI" | "SOAP" | "Other";
  repo: string;
  owner: string;
  environments: string[];
  hasSpec: boolean;
  specFormat: string;
  ciCdIntegrated: boolean;
  hasWorkspace: boolean;
  repoLinked: boolean;
  inCatalog: boolean;
  catalogIngestion: "provisioned" | "gateway" | "insights" | "migration" | "manual" | "";
}

export interface GovernanceStage {
  stage: "design" | "commit" | "cicd" | "deploy" | "ongoing";
  enabled: boolean;
  rules: string[];
}

export interface BackfillStrategy {
  gatewayImport: boolean;
  insightsAgent: boolean;
  workspaceMigration: boolean;
  cliBatchImport: boolean;
  manual: boolean;
  estimatedExistingApis: string;
  backfillNotes: string;
}

export interface DiscoveryAnswers {
  provisioningFlow: string;
  specLocation: string;
  catalogSystem: string;
  secretHandling: string;
  painPoints: string[];
  idealStakeholder: string;
  pocTarget: string;
}

export interface ArchitectureFormData {
  companyName: string;
  primaryDomain: string;
  scm: string;
  ciCd: string;
  gateway: string;
  cloud: string;
  idp: string;
  secretManager: string;
  devPortal: string;
  monitoring: string;
  specHosting: string;
  observability: string;
  currentPostmanUsage: string;
  postmanPlan: string;
  workspaceStrategy: string;
  namingConvention: string;
  services: ServiceEntry[];
  deploymentTargets: string[];
  governanceRules: string[];
  governanceStages: GovernanceStage[];
  governanceGroupScope: string;
  backfill: BackfillStrategy;
  discovery: DiscoveryAnswers;
  notes: string;
}

export async function getAssignableProjects() {
  const session = await requireAuth();
  return prisma.project.findMany({
    where: { ownerUserId: session.userId, status: "active" },
    select: { id: true, name: true, primaryDomain: true, engagementStage: true },
    orderBy: { updatedAt: "desc" },
  });
}

function buildOpenAPISpec(data: ArchitectureFormData): string {
  const info = [
    `# ${data.companyName} — System Architecture & Service Template`,
    `# Generated by CortexLab Architecture Mapper`,
    `# ${new Date().toISOString()}`,
    "",
    "openapi: '3.0.3'",
    "info:",
    `  title: ${data.companyName} Service Constellation`,
    `  version: '1.0.0'`,
    `  description: |`,
    `    Architecture map for ${data.companyName}.`,
    `    Domain: ${data.primaryDomain}`,
    `    ${data.services.length} services across ${new Set(data.services.map((s) => s.domain)).size} domain(s).`,
    "",
    "    Infrastructure:",
    `      SCM: ${data.scm}`,
    `      CI/CD: ${data.ciCd}`,
    `      Gateway: ${data.gateway}`,
    `      Cloud: ${data.cloud}`,
    `      IDP: ${data.idp || "N/A"}`,
    `      Secrets: ${data.secretManager}`,
    `      Dev Portal: ${data.devPortal || "N/A"}`,
    `      Monitoring: ${data.monitoring || "N/A"}`,
    `      Spec Hosting: ${data.specHosting || "N/A"}`,
    `      Observability: ${data.observability || "N/A"}`,
    "",
    `    Postman Integration Points:`,
    `      SCM -> Filesystem integration (workspace linked to repo)`,
    `      CI/CD -> Postman CLI runs tests in pipeline; results feed to catalog`,
    `      Gateway -> Gateway apps import deployed APIs; CLI-based import from gateway specs`,
    `      Secrets -> Pre-request scripts resolve secrets at runtime; no secrets stored in Postman`,
    `      Monitoring -> Postman Monitors -> Slack/Teams/PagerDuty; Monitor data feeds catalog`,
    `      Spec Hosting -> Spec Hub replaces SwaggerHub; or import from SwaggerHub into Spec Hub`,
    `      Observability -> Insights Agent captures runtime traffic; Agent Mode correlates with third-party data via MCP`,
    `      IDP -> Postman API calls to create workspace, collections, environments at provisioning time`,
    "",
    `    Postman:`,
    `      Current Usage: ${data.currentPostmanUsage}`,
    `      Plan: ${data.postmanPlan}`,
    `      Workspace Strategy: ${data.workspaceStrategy}`,
    `      Naming Convention: ${data.namingConvention}`,
    "",
    `    Governance Architecture:`,
  ];

  const activeStages = data.governanceStages.filter((g) => g.enabled);
  if (activeStages.length > 0) {
    for (const gs of activeStages) {
      info.push(`      ${gs.stage}:`);
      for (const r of gs.rules) {
        info.push(`        - ${r}`);
      }
    }
  }
  if (data.governanceGroupScope) {
    info.push(`      Governance Group Scope: ${data.governanceGroupScope}`);
  }
  info.push("");

  if (data.governanceRules.length > 0) {
    info.push("    Custom Governance Rules:");
    for (const rule of data.governanceRules) {
      info.push(`      - ${rule}`);
    }
    info.push("");
  }

  if (data.deploymentTargets.length > 0) {
    info.push("    Deployment Targets:");
    for (const target of data.deploymentTargets) {
      info.push(`      - ${target}`);
    }
    info.push("");
  }

  if (data.backfill.estimatedExistingApis) {
    info.push(`    Backfill Strategy (est. ${data.backfill.estimatedExistingApis} existing APIs):`);
    if (data.backfill.gatewayImport) info.push("      - Gateway import (bulk-import from gateway specs)");
    if (data.backfill.insightsAgent) info.push("      - Insights Agent (runtime discovery of shadow APIs)");
    if (data.backfill.workspaceMigration) info.push("      - Workspace migration (filesystem integration + catalog tagging)");
    if (data.backfill.cliBatchImport) info.push("      - CLI batch import (specs from repos)");
    if (data.backfill.manual) info.push("      - Manual (Agent Mode spec generation from observed behavior)");
    if (data.backfill.backfillNotes) info.push(`      Notes: ${data.backfill.backfillNotes}`);
    info.push("");
  }

  const paths: string[] = ["paths:"];
  const tags: string[] = ["tags:"];
  const tagSet = new Set<string>();

  for (const svc of data.services) {
    const tag = `${svc.domain}-${svc.name}`;
    if (!tagSet.has(svc.domain)) {
      tagSet.add(svc.domain);
      tags.push(`  - name: ${svc.domain}`);
      tags.push(`    description: ${svc.domain} domain services`);
    }

    const basePath = `/${svc.domain}/${svc.name}`;
    paths.push(`  ${basePath}:`);
    paths.push(`    get:`);
    paths.push(`      summary: ${svc.purpose}`);
    paths.push(`      operationId: get-${tag}`);
    paths.push(`      tags: [${svc.domain}]`);
    paths.push(`      x-service-type: ${svc.type}`);
    paths.push(`      x-repo: ${svc.repo}`);
    paths.push(`      x-owner: ${svc.owner}`);
    paths.push(`      x-has-spec: ${svc.hasSpec}`);
    paths.push(`      x-spec-format: ${svc.specFormat || "none"}`);
    paths.push(`      x-ci-cd-integrated: ${svc.ciCdIntegrated}`);
    paths.push(`      x-has-workspace: ${svc.hasWorkspace}`);
    paths.push(`      x-repo-linked: ${svc.repoLinked}`);
    paths.push(`      x-in-catalog: ${svc.inCatalog}`);
    paths.push(`      x-catalog-ingestion: ${svc.catalogIngestion || "provisioned"}`);
    if (svc.environments.length > 0) {
      paths.push(`      x-environments: [${svc.environments.join(", ")}]`);
    }
    paths.push(`      responses:`);
    paths.push(`        '200':`);
    paths.push(`          description: ${svc.purpose}`);
    paths.push("");
  }

  return [...info, ...tags, "", ...paths].join("\n");
}

function buildTopologyNodes(data: ArchitectureFormData) {
  const nodes: Array<{
    id: string;
    type: string;
    name: string;
    metadata: Record<string, unknown>;
    evidenceIds: string[];
    confidence: number;
  }> = [];

  const edges: Array<{
    from: string;
    to: string;
    type: string;
    evidenceIds: string[];
    confidence: number;
  }> = [];

  for (const svc of data.services) {
    const nodeId = `${svc.domain}-${svc.name}`.toLowerCase().replace(/\s+/g, "-");
    nodes.push({
      id: nodeId,
      type: "SERVICE",
      name: `${svc.domain}/${svc.name}`,
      metadata: {
        domain: svc.domain,
        purpose: svc.purpose,
        apiType: svc.type,
        repo: svc.repo,
        owner: svc.owner,
        environments: svc.environments,
        hasSpec: svc.hasSpec,
        specFormat: svc.specFormat,
        ciCdIntegrated: svc.ciCdIntegrated,
        hasWorkspace: svc.hasWorkspace,
        repoLinked: svc.repoLinked,
        inCatalog: svc.inCatalog,
        catalogIngestion: svc.catalogIngestion,
      },
      evidenceIds: ["architect-mapper"],
      confidence: 0.95,
    });
  }

  if (data.gateway) {
    nodes.push({
      id: "gateway",
      type: "GATEWAY",
      name: data.gateway,
      metadata: { product: data.gateway },
      evidenceIds: ["architect-mapper"],
      confidence: 0.95,
    });
    for (const svc of data.services) {
      const nodeId = `${svc.domain}-${svc.name}`.toLowerCase().replace(/\s+/g, "-");
      edges.push({
        from: "gateway",
        to: nodeId,
        type: "ROUTES_THROUGH",
        evidenceIds: ["architect-mapper"],
        confidence: 0.8,
      });
    }
  }

  if (data.idp && data.idp !== "None") {
    nodes.push({
      id: "identity-provider",
      type: "IDENTITY_PROVIDER",
      name: data.idp,
      metadata: {
        product: data.idp,
        postmanIntegration: "Postman API calls to create workspace, collections, environments at provisioning time",
      },
      evidenceIds: ["architect-mapper"],
      confidence: 0.9,
    });
    for (const svc of data.services) {
      const nodeId = `${svc.domain}-${svc.name}`.toLowerCase().replace(/\s+/g, "-");
      edges.push({
        from: nodeId,
        to: "identity-provider",
        type: "AUTHENTICATES_WITH",
        evidenceIds: ["architect-mapper"],
        confidence: 0.8,
      });
    }
  }

  if (data.monitoring && data.monitoring !== "None") {
    nodes.push({
      id: "monitoring",
      type: "EXTERNAL_SYSTEM",
      name: data.monitoring,
      metadata: {
        product: data.monitoring,
        role: "monitoring",
        postmanIntegration: "Postman Monitors -> Slack/Teams/PagerDuty; Monitor data feeds catalog Monitor tab",
      },
      evidenceIds: ["architect-mapper"],
      confidence: 0.85,
    });
  }

  if (data.observability && data.observability !== "None") {
    nodes.push({
      id: "observability",
      type: "EXTERNAL_SYSTEM",
      name: data.observability,
      metadata: {
        product: data.observability,
        role: "observability",
        postmanIntegration: "Insights Agent captures runtime traffic; Agent Mode correlates with third-party data via MCP",
      },
      evidenceIds: ["architect-mapper"],
      confidence: 0.85,
    });
  }

  if (data.secretManager && data.secretManager !== "Environment Variables") {
    nodes.push({
      id: "secret-manager",
      type: "EXTERNAL_SYSTEM",
      name: data.secretManager,
      metadata: {
        product: data.secretManager,
        role: "secrets",
        postmanIntegration: "Pre-request scripts resolve secrets at runtime; no secrets stored in Postman",
      },
      evidenceIds: ["architect-mapper"],
      confidence: 0.9,
    });
  }

  return { nodes, edges };
}

export async function submitArchitectureMap(
  projectId: string,
  data: ArchitectureFormData,
) {
  const session = await requireAuth();

  const project = await prisma.project.findFirst({
    where: { id: projectId, ownerUserId: session.userId },
    select: { id: true, name: true },
  });
  if (!project) return { error: "Project not found" };

  const specContent = buildOpenAPISpec(data);
  const { nodes, edges } = buildTopologyNodes(data);
  const briefMarkdown = generateDiscoveryBrief(data);
  const topologyMarkdown = generateTopologyMarkdown(data, nodes, edges);

  // ── 1. Persist project, topology, and discovery artifacts ──────────
  await prisma.$transaction(async (tx) => {
    const ciLabel = data.ciCd || "CI/CD";
    const pocDeliverables: PocDeliverable[] = [
      { ...DEFAULT_POC_DELIVERABLES[0], description: `Working ${ciLabel} workflow that provisions Postman workspace + collections + environments + tests from a single trigger` },
      { ...DEFAULT_POC_DELIVERABLES[1], description: `Working ${ciLabel} integration that runs smoke + contract tests on push and reports results` },
      { ...DEFAULT_POC_DELIVERABLES[2] },
      { ...DEFAULT_POC_DELIVERABLES[3] },
    ];

    await tx.project.update({
      where: { id: projectId },
      data: {
        serviceTemplateContent: specContent,
        serviceTemplateType: "openapi",
        serviceTemplateFileName: `${data.companyName.toLowerCase().replace(/\s+/g, "-")}-architecture.yaml`,
        serviceTemplateNotes: data.notes || null,
        primaryDomain: data.primaryDomain || undefined,
        pocDeliverablesJson: pocDeliverables as unknown as Prisma.InputJsonValue,
      },
    });

    // CURRENT_TOPOLOGY phase artifact
    const existingTopo = await tx.phaseArtifact.findFirst({
      where: { projectId, phase: "CURRENT_TOPOLOGY" },
      orderBy: { version: "desc" },
      select: { version: true },
    });

    await tx.phaseArtifact.create({
      data: {
        projectId,
        phase: "CURRENT_TOPOLOGY",
        version: (existingTopo?.version ?? 0) + 1,
        status: "CLEAN",
        contentJson: {
          nodes: nodes as unknown as Prisma.InputJsonValue,
          edges: edges as unknown as Prisma.InputJsonValue,
          reasoningSummary: `Architecture mapped via Architecture Mapper. ${nodes.length} nodes, ${edges.length} edges. Infrastructure: ${data.scm} / ${data.ciCd} / ${data.cloud}.`,
          source: "architect-mapper",
        } as Prisma.InputJsonValue,
        contentMarkdown: topologyMarkdown,
      },
    });

    // DISCOVERY phase artifact
    const existingDiscPhase = await tx.phaseArtifact.findFirst({
      where: { projectId, phase: "DISCOVERY" },
      orderBy: { version: "desc" },
      select: { version: true },
    });

    await tx.phaseArtifact.create({
      data: {
        projectId,
        phase: "DISCOVERY",
        version: (existingDiscPhase?.version ?? 0) + 1,
        status: "CLEAN",
        contentJson: {
          companyName: data.companyName,
          primaryDomain: data.primaryDomain,
          infrastructure: { scm: data.scm, ciCd: data.ciCd, gateway: data.gateway, cloud: data.cloud, idp: data.idp, secretManager: data.secretManager, monitoring: data.monitoring, specHosting: data.specHosting, observability: data.observability },
          postman: { plan: data.postmanPlan, workspaceStrategy: data.workspaceStrategy, namingConvention: data.namingConvention, currentUsage: data.currentPostmanUsage },
          serviceCount: data.services.length,
          discovery: data.discovery as unknown as Prisma.InputJsonValue,
          source: "architect-mapper",
        } as Prisma.InputJsonValue,
        contentMarkdown: briefMarkdown,
      },
    });

    // DiscoveryArtifact (upsert — update if exists, create if not)
    const existingDiscovery = await tx.discoveryArtifact.findFirst({
      where: { projectId },
      orderBy: { version: "desc" },
      select: { id: true, version: true },
    });

    const discoveryPayload = {
      industry: data.primaryDomain || "",
      engineeringSize: "",
      publicApiPresence: "",
      cloudGatewaySignals: `Gateway: ${data.gateway}, Cloud: ${data.cloud}, IDP: ${data.idp || "N/A"}`,
      hypothesis: `Embed Postman into ${data.companyName}'s API lifecycle using ${data.workspaceStrategy} workspace strategy with ${data.namingConvention} naming convention.`,
      generatedBriefMarkdown: briefMarkdown,
    };

    if (existingDiscovery) {
      await tx.discoveryArtifact.update({
        where: { id: existingDiscovery.id },
        data: discoveryPayload,
      });
    } else {
      await tx.discoveryArtifact.create({
        data: { projectId, version: 1, ...discoveryPayload },
      });
    }
  });

  // ── 2. Ingest architecture data as evidence document ───────────────
  const fullDocument = [briefMarkdown, "", "---", "", topologyMarkdown, "", "---", "", "## Service Template (OpenAPI)", "", specContent].join("\n");

  let snapshotId: string | null = null;
  let impactedPhases: string[] = [];

  try {
    await ingestDocument({
      projectId,
      sourceType: "ARCHITECTURE_MAP",
      title: `${data.companyName} Architecture Map`,
      rawText: fullDocument,
      externalId: `architect-mapper-${projectId}`,
    });

    // ── 3. Create evidence snapshot and trigger cascade ───────────────
    const snapshot = await createEvidenceSnapshot(projectId);
    snapshotId = snapshot.snapshotId;

    const impact = await runImpactAnalysis(projectId, snapshot.snapshotId, "INGEST");
    impactedPhases = impact.impactedPhases;
  } catch (cascadeErr) {
    console.warn("[architect] Cascade snapshot/impact failed (non-fatal):", cascadeErr);
  }

  await awardXp(
    session.userId,
    "architecture_mapped",
    100,
    projectId,
    { serviceCount: data.services.length },
  );

  revalidatePath(`/projects/${projectId}`);
  revalidatePath(`/projects/${projectId}/discovery`);
  revalidatePath(`/projects/${projectId}/discovery/brief`);
  revalidatePath(`/projects/${projectId}/topology`);
  revalidatePath(`/projects/${projectId}/updates`);
  return { success: true, projectName: project.name, snapshotId, impactedPhases };
}

function generateTopologyMarkdown(
  data: ArchitectureFormData,
  nodes: ReturnType<typeof buildTopologyNodes>["nodes"],
  edges: ReturnType<typeof buildTopologyNodes>["edges"],
): string {
  const lines: string[] = [
    `# ${data.companyName} — System Topology`,
    "",
    "## Infrastructure",
    `| Layer | Technology | Postman Integration |`,
    `|-------|-----------|---------------------|`,
    `| SCM | ${data.scm} | Filesystem integration (workspace linked to repo) |`,
    `| CI/CD | ${data.ciCd} | Postman CLI runs tests in pipeline; results feed to catalog |`,
    `| Gateway | ${data.gateway || "N/A"} | Gateway apps import deployed APIs; CLI-based import from gateway specs |`,
    `| Cloud | ${data.cloud} | — |`,
    `| IDP | ${data.idp || "N/A"} | Postman API calls to create workspace, collections, environments at provisioning time |`,
    `| Secrets | ${data.secretManager || "N/A"} | Pre-request scripts resolve secrets at runtime; no secrets stored in Postman |`,
    `| Dev Portal | ${data.devPortal || "N/A"} | — |`,
    `| Monitoring | ${data.monitoring || "N/A"} | Postman Monitors -> alerting; Monitor data feeds catalog |`,
    `| Spec Hosting | ${data.specHosting || "N/A"} | Spec Hub replaces SwaggerHub; or import from SwaggerHub into Spec Hub |`,
    `| Observability | ${data.observability || "N/A"} | Insights Agent captures runtime traffic; Agent Mode correlates via MCP |`,
    "",
    "## Nodes",
    "| Name | Type | Confidence | Evidence |",
    "|------|------|------------|----------|",
  ];

  for (const n of nodes) {
    lines.push(`| ${n.name} | ${n.type} | ${n.confidence} | ${n.evidenceIds.join(", ")} |`);
  }

  lines.push("", "## Edges", "| Connection | Type | Confidence |", "|------------|------|------------|");
  for (const e of edges) {
    lines.push(`| ${e.from} → ${e.to} | ${e.type} | ${e.confidence} |`);
  }

  const activeStages = data.governanceStages.filter((g) => g.enabled);
  if (activeStages.length > 0) {
    lines.push("", "## Governance Architecture");
    lines.push("| Stage | What Gets Checked | How |");
    lines.push("|-------|-------------------|-----|");
    const stageDescriptions: Record<string, [string, string]> = {
      design: ["Spec linting, naming conventions, versioning, deprecation", "Spec Hub governance rules (Spectral) — real-time inline feedback"],
      commit: ["Spec compliance, breaking change detection", "Git pre-commit hooks or PR checks via Postman CLI"],
      cicd: ["Contract tests, smoke tests, spec quality", "Postman CLI in pipeline — blocks deployment on failure"],
      deploy: ["Post-deployment smoke tests, environment validation", "Postman CLI post-deploy job"],
      ongoing: ["Schema drift detection, production health", "Monitors + Insights Agent — feeds API Catalog"],
    };
    for (const gs of activeStages) {
      const [what, how] = stageDescriptions[gs.stage] ?? ["", ""];
      lines.push(`| ${gs.stage} | ${what} | ${how} |`);
      if (gs.rules.length > 0) {
        for (const r of gs.rules) lines.push(`|  | ↳ ${r} | |`);
      }
    }
  }

  if (data.backfill.estimatedExistingApis) {
    lines.push("", `## Backfill Strategy (est. ${data.backfill.estimatedExistingApis} existing APIs)`);
    lines.push("| Method | Selected | Priority |");
    lines.push("|--------|----------|----------|");
    const methods = [
      ["Gateway import", data.backfill.gatewayImport, "1 — Fastest"],
      ["Insights Agent (runtime discovery)", data.backfill.insightsAgent, "2 — Catches shadow APIs"],
      ["Workspace migration", data.backfill.workspaceMigration, "3 — For existing Postman APIs"],
      ["CLI batch import", data.backfill.cliBatchImport, "4 — Specs in repos but not in Postman"],
      ["Manual (Agent Mode)", data.backfill.manual, "5 — Last resort"],
    ] as const;
    for (const [name, selected, priority] of methods) {
      lines.push(`| ${name} | ${selected ? "✓" : "—"} | ${priority} |`);
    }
    if (data.backfill.backfillNotes) lines.push("", `**Notes:** ${data.backfill.backfillNotes}`);
  }

  return lines.join("\n");
}

function generateDiscoveryBrief(data: ArchitectureFormData): string {
  const domains = [...new Set(data.services.map((s) => s.domain))];
  const lines = [
    `# ${data.companyName} Discovery Brief`,
    "",
    `## Overview`,
    `${data.companyName} operates ${data.services.length} services across ${domains.length} domain(s): ${domains.join(", ")}.`,
    "",
    `## Current Infrastructure & Postman Integration`,
    `| Component | Technology | Postman Integration |`,
    `|-----------|-----------|---------------------|`,
    `| SCM | ${data.scm} | Filesystem integration (workspace linked to repo); ${data.scm === "GitHub" ? "GitHub Actions" : data.scm === "GitLab" ? "GitLab CI" : "CI"} for test execution |`,
    `| CI/CD | ${data.ciCd} | Postman CLI runs tests in pipeline; results feed to catalog |`,
    `| Gateway | ${data.gateway || "N/A"} | Gateway apps import deployed APIs; or CLI-based import from gateway specs |`,
    `| Cloud | ${data.cloud} | — |`,
    `| IDP | ${data.idp || "N/A"} | Postman API calls to create workspace, collections, environments at provisioning time |`,
    `| Secrets | ${data.secretManager || "N/A"} | Pre-request scripts resolve secrets at runtime; no secrets stored in Postman |`,
    `| Monitoring | ${data.monitoring || "N/A"} | Postman Monitors -> Slack/Teams/PagerDuty; Monitor data feeds catalog |`,
    `| Spec Hosting | ${data.specHosting || "N/A"} | Spec Hub replaces SwaggerHub; or import into Spec Hub |`,
    `| Observability | ${data.observability || "N/A"} | Insights Agent captures runtime traffic; Agent Mode correlates via MCP |`,
    "",
    `## Postman Status`,
    `- **Current Usage:** ${data.currentPostmanUsage}`,
    `- **Plan:** ${data.postmanPlan}`,
    `- **Workspace Strategy:** ${data.workspaceStrategy}`,
    `- **Naming Convention:** \`${data.namingConvention}\``,
    "",
    `## API Catalog Readiness`,
    `| Service | Workspace | Repo Linked | In Catalog | Ingestion Path |`,
    `|---------|-----------|-------------|------------|----------------|`,
    ...data.services.map((s) =>
      `| ${s.domain}/${s.name} | ${s.hasWorkspace ? "✓" : "✗"} | ${s.repoLinked ? "✓" : "✗"} | ${s.inCatalog ? "✓" : "✗"} | ${s.catalogIngestion || "provisioned"} |`,
    ),
    "",
    `## Services`,
    ...data.services.map((s) =>
      `- **${s.domain}/${s.name}** (${s.type}) — ${s.purpose} — Owner: ${s.owner} — Repo: ${s.repo} — Spec: ${s.hasSpec ? s.specFormat : "None"} — CI/CD: ${s.ciCdIntegrated ? "Yes" : "No"} — Envs: ${s.environments.join(", ")}`,
    ),
    "",
    `## Deployment Targets`,
    ...data.deploymentTargets.map((t) => `- ${t}`),
    "",
  ];

  if (data.discovery.provisioningFlow || data.discovery.painPoints.length > 0) {
    lines.push("## Discovery Call Notes");
    if (data.discovery.provisioningFlow) lines.push(`### Provisioning Flow`, data.discovery.provisioningFlow, "");
    if (data.discovery.specLocation) lines.push(`### Spec Location`, data.discovery.specLocation, "");
    if (data.discovery.catalogSystem) lines.push(`### Current Catalog / System of Record`, data.discovery.catalogSystem, "");
    if (data.discovery.secretHandling) lines.push(`### Secret Handling`, data.discovery.secretHandling, "");
    if (data.discovery.painPoints.length > 0) {
      lines.push("### Pain Points");
      for (const p of data.discovery.painPoints) lines.push(`- ${p}`);
      lines.push("");
    }
    if (data.discovery.idealStakeholder) lines.push(`### Ideal Stakeholder`, data.discovery.idealStakeholder, "");
    if (data.discovery.pocTarget) lines.push(`### POC Target`, data.discovery.pocTarget, "");
  }

  const activeStages = data.governanceStages.filter((g) => g.enabled);
  if (activeStages.length > 0 || data.governanceRules.length > 0) {
    lines.push("## Governance Architecture");
    lines.push("Governance is embedded in the architecture, not a separate step.");
    lines.push("");
    if (activeStages.length > 0) {
      for (const gs of activeStages) {
        const stageLabels: Record<string, string> = {
          design: "At Design Time",
          commit: "At Commit Time",
          cicd: "At CI/CD Time",
          deploy: "At Deploy Time",
          ongoing: "Ongoing",
        };
        lines.push(`### ${stageLabels[gs.stage] ?? gs.stage}`);
        for (const r of gs.rules) lines.push(`- ${r}`);
        lines.push("");
      }
    }
    if (data.governanceRules.length > 0) {
      lines.push("### Custom Rules");
      for (const r of data.governanceRules) lines.push(`- ${r}`);
      lines.push("");
    }
    if (data.governanceGroupScope) {
      lines.push(`**Governance Group Scope:** ${data.governanceGroupScope}`);
      lines.push("");
    }
  }

  if (data.backfill.estimatedExistingApis) {
    lines.push(`## Backfill Strategy`);
    lines.push(`Estimated existing APIs: **${data.backfill.estimatedExistingApis}**`);
    lines.push("");
    lines.push("Priority order:");
    if (data.backfill.gatewayImport) lines.push("1. **Gateway import** (fastest) — bulk-import from gateway specs");
    if (data.backfill.insightsAgent) lines.push("2. **Insights Agent** (runtime discovery) — catches shadow APIs not documented anywhere");
    if (data.backfill.workspaceMigration) lines.push("3. **Workspace migration** — enable filesystem integration and tag workspaces for catalog");
    if (data.backfill.cliBatchImport) lines.push("4. **CLI batch import** — for APIs with specs in repos but not in Postman");
    if (data.backfill.manual) lines.push("5. **Manual** (last resort) — Agent Mode can help generate specs from observed behavior");
    if (data.backfill.backfillNotes) lines.push("", `**Notes:** ${data.backfill.backfillNotes}`);
    lines.push("");
  }

  if (data.notes) lines.push(`## Notes`, data.notes, "");

  return lines.join("\n");
}
